### ISSUE TITLE
Document job ports, port paths, and port path interpolation

### ISSUE THREAD

**Issue by njhale** [acorn-io/docs#9]
Add docs for the following new features:

- ports on jobs
- paths on ports
- interpolation of paths on ports

These features were implemented by: https://github.com/acorn-io/runtime/pull/2318#issue-1976254104
First runtime release that includes them: https://github.com/acorn-io/runtime/releases/tag/v0.9.2

**Comment by cjellick** [comment]
@njhale - FYI - I found this in my "Misplaced" board here: https://github.com/orgs/acorn-io/projects/1/views/37

If an issue has no milestone, it should stay in "Needs Triaged". 
I will move this to Backend Stream and leave assigned to you and in Next Up. But, if something is in Backend Stream (instead of Backlog), that means it legitimately needs to be picked up soon. Things should not pile up in Backend Stream; that's what back log is for
 
I had to create the milestones for this repo because they didnt exiset
